/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CProduct;
import Model.MDBConnection;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ProductManagement extends javax.swing.JFrame {

    /**
     * Creates new form ProductManagement
     */
    public ProductManagement() {
        initComponents();
        id_autoincrement();
         date_create.setDate(new java.util.Date());
    }
    public void id_autoincrement(){
    
           try {
            Connection conn = MDBConnection.createConnection();
            String sql = "SELECT COALESCE(MAX(ProductID), 0) FROM Product";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            int nextId = 1; // Default ID if no records are found

            if (rs.next()) {
                int maxId = rs.getInt(1);
                nextId = maxId + 1;
            }

            txt_productid.setText(String.valueOf(nextId));
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void clearFields(){
    
        txt_productname.setText("");
        txt_price.setText("");
        date_create.setDate(null);
        date_modify.setDate(null);
        date_warranty.setDate(null);
    
    }
   /* public void reorderProductIDs() {
   
    
    try {
        Connection conn = MDBConnection.createConnection();
         
         Statement stmt = conn.createStatement();
         String setCounterSQL = "SET @count = 0;";
        stmt.execute(setCounterSQL); 
         String reorderSQL = "UPDATE Product SET ProductID = @count:= @count + 1 ORDER BY ProductID;";
        stmt.executeUpdate(reorderSQL);

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_productid = new javax.swing.JTextField();
        txt_productname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_membername = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_issue = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_issue1 = new javax.swing.JButton();
        btn_issue2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        date_create = new com.toedter.calendar.JDateChooser();
        date_warranty = new com.toedter.calendar.JDateChooser();
        date_modify = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Images\\pm.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Product ID");

        txt_productid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productidActionPerformed(evt);
            }
        });

        txt_productname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");

        txt_membername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_membername.setText("Price ");

        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("CreateDate");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ModifyDate");

        btn_issue.setBackground(new java.awt.Color(0, 153, 153));
        btn_issue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_issue.setForeground(new java.awt.Color(255, 255, 255));
        btn_issue.setText("Update");
        btn_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issueActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 153, 153));
        btn_clear.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Warranty");

        btn_issue1.setBackground(new java.awt.Color(0, 153, 153));
        btn_issue1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_issue1.setForeground(new java.awt.Color(255, 255, 255));
        btn_issue1.setText("Add");
        btn_issue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issue1ActionPerformed(evt);
            }
        });

        btn_issue2.setBackground(new java.awt.Color(0, 153, 153));
        btn_issue2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_issue2.setForeground(new java.awt.Color(255, 255, 255));
        btn_issue2.setText("Delete");
        btn_issue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issue2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setText("Product Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(180, 180, 180))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_membername)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_productid, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_price)
                                    .addComponent(date_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date_warranty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(date_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_issue1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_issue)
                        .addGap(18, 18, 18)
                        .addComponent(btn_issue2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clear)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_membername)
                                .addGap(50, 50, 50))
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_productid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(date_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date_warranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date_modify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_issue1)
                    .addComponent(btn_issue)
                    .addComponent(btn_issue2)
                    .addComponent(btn_clear))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_productidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productidActionPerformed
           // Fetch product details based on ID
        int productid = Integer.parseInt(txt_productid.getText());
        if (productid <= 0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Product ID");
            return;
        }

        try {
            Connection conn = MDBConnection.createConnection();
            String sql = "SELECT ProductName, Price, CreateDate, ModifyDate, Warranty_Date FROM Product WHERE ProductID = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, productid);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_productname.setText(rs.getString("ProductName"));
                txt_price.setText(String.valueOf(rs.getInt("Price")));
                date_create.setDate(rs.getDate("CreateDate"));
                date_modify.setDate(rs.getDate("ModifyDate"));
                date_warranty.setDate(rs.getDate("Warranty_Date"));
            } else {
                JOptionPane.showMessageDialog(null, "Product ID not found");
                clearFields(); // Clear fields if ID not found
            }

            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error retrieving product details: " + e.getMessage());
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_txt_productidActionPerformed

    private void txt_productnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productnameActionPerformed

       

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productnameActionPerformed

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void btn_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issueActionPerformed
       
        if (!validateProductId() || !validateProductName() || !validatePrice() || !validateDates()) {
            return; // Exit if validation fails
        }
        int productid = Integer.parseInt(txt_productid.getText());
        String productname = txt_productname.getText();
        int price = Integer.parseInt(txt_price.getText());
        java.util.Date utilCreateDate = date_create.getDate();
        java.sql.Date sqlcreatedate = new java.sql.Date(utilCreateDate.getTime());
        java.util.Date utildate_modify = date_modify.getDate();
        java.sql.Date sqlmodifydate = new java.sql.Date(utildate_modify.getTime());
        java.util.Date date_warantydates = date_warranty.getDate();
        java.sql.Date sqlwarantydate = new java.sql.Date(date_warantydates.getTime());

        CProduct cp = new CProduct();
        cp.updateProduct(productid, productname, price, sqlcreatedate, sqlmodifydate, sqlwarantydate);
        id_autoincrement();
       clearFields();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_issueActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
            clearFields();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_issue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issue1ActionPerformed
   if (!validateProductName() || !validatePrice() || !validateDates()) {
            return; // Exit if validation fails
        }
        String productname = txt_productname.getText();
        int price = Integer.parseInt(txt_price.getText());
        java.util.Date utilCreateDate = date_create.getDate();
        java.sql.Date sqlcreatedate = new java.sql.Date(utilCreateDate.getTime());
        java.util.Date utildate_modify = date_modify.getDate();
        java.sql.Date sqlmodifydate = new java.sql.Date(utildate_modify.getTime());
        java.util.Date date_warantydates = date_warranty.getDate();
        java.sql.Date sqlwarantydate = new java.sql.Date(date_warantydates.getTime());
        int qty = 0; // Default quantity

        CProduct cp = new CProduct();
        cp.addProduct(productname, price, sqlcreatedate, sqlmodifydate, sqlwarantydate, qty);

        clearFields();
        id_autoincrement();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_issue1ActionPerformed

    private void btn_issue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issue2ActionPerformed
      if (!validateProductId()) {
            return; // Exit if validation fails
        }
        int productid = Integer.parseInt(txt_productid.getText());
        CProduct cp = new CProduct();
        cp.deleteProduct(productid);
        clearFields();
        id_autoincrement();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_issue2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        VProductManagerDashboard vpmd = new VProductManagerDashboard();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
private boolean validateProductId() {
    String productIdText = txt_productid.getText().trim();
    if (productIdText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Product ID cannot be empty");
        return false;
    }
    try {
        Integer.parseInt(productIdText);
        return true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Product ID must be a valid number");
        return false;
    }
}

private boolean validateProductName() {
    if (txt_productname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Product Name cannot be empty");
        return false;
    }
    return true;
}

private boolean validatePrice() {
    String priceText = txt_price.getText().trim();
    if (priceText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Price cannot be empty");
        return false;
    }
    try {
        int price = Integer.parseInt(priceText);
        if (price <= 0) {
            JOptionPane.showMessageDialog(null, "Price must be greater than zero");
            return false;
        }
        return true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Price must be a valid number");
        return false;
    }
}

private boolean validateDates() {
    if (date_create.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Create Date cannot be empty");
        return false;
    }
    if (date_modify.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Modify Date cannot be empty");
        return false;
    }
    if (date_warranty.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Warranty Date cannot be empty");
        return false;
    }
    if (date_create.getDate().after(date_modify.getDate())) {
        JOptionPane.showMessageDialog(null, "Create Date cannot be after Modify Date");
        return false;
    }
    return true;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_issue;
    private javax.swing.JButton btn_issue1;
    private javax.swing.JButton btn_issue2;
    private com.toedter.calendar.JDateChooser date_create;
    private com.toedter.calendar.JDateChooser date_modify;
    private com.toedter.calendar.JDateChooser date_warranty;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_membername;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_productid;
    private javax.swing.JTextField txt_productname;
    // End of variables declaration//GEN-END:variables
}
