/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Model.MDBConnection;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author USER
 */
public class VCheckBulkOrderCashire extends javax.swing.JFrame {

    /**
     * Creates new form VCheckOrderSalesmanager
     */
    public VCheckBulkOrderCashire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_display6 = new javax.swing.JButton();
        txt_orderid2 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextArea6 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        btn_search7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bulk Order Name");

        txt_display6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txt_display6.setText("Search");
        txt_display6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_display6ActionPerformed(evt);
            }
        });

        txt_orderid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_orderid2ActionPerformed(evt);
            }
        });

        TextArea6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bulk OrderID", "OrderDate", "Qty", "TotalPrice", "ProductName"
            }
        ));
        jScrollPane7.setViewportView(TextArea6);

        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btn_search7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_search7.setText("Display");
        btn_search7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txt_orderid2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_display6)
                .addGap(31, 31, 31)
                .addComponent(btn_search7)
                .addGap(28, 28, 28)
                .addComponent(jButton9)
                .addGap(44, 44, 44))
            .addComponent(jScrollPane7)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_orderid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9)
                    .addComponent(txt_display6)
                    .addComponent(btn_search7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(974, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_display6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_display6ActionPerformed
        // Validate the Order ID input
   String productNameText = txt_orderid2.getText();  // Assuming txt_orderid2 is used for entering Product Name
if (productNameText.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Product Name cannot be empty", "Validation Error", JOptionPane.WARNING_MESSAGE);
    return;
}

// Clear previous data
DefaultTableModel model = (DefaultTableModel) TextArea6.getModel();
model.setRowCount(0); // Clear existing rows

try (Connection con = MDBConnection.createConnection();
     PreparedStatement pst = con.prepareStatement("SELECT * FROM bulkorder WHERE ProductName = ?")) {
    
    pst.setString(1, productNameText);  // Set the product name parameter for the query
    
    try (ResultSet rst = pst.executeQuery()) {
        if (rst.next()) {
            // Add the retrieved data as a row in the table model
            model.addRow(new Object[]{
                rst.getInt("BulkOrderID"),
                rst.getDate("BulkOrderDate"),
                rst.getInt("Qty"),
                rst.getInt("TotalPrice"),
                rst.getString("ProductName")
            });
        } else {
            JOptionPane.showMessageDialog(null, "Order not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_display6ActionPerformed

    private void txt_orderid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_orderid2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_orderid2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        this.setVisible(false);
        VSalesManagerDashboard vpmd =new VSalesManagerDashboard();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btn_search7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search7ActionPerformed
        // Clear previous data
        DefaultTableModel model = (DefaultTableModel) TextArea6.getModel();
        model.setRowCount(0); // Clear existing rows

        try (Connection con = MDBConnection.createConnection();
            Statement st = con.createStatement();
            ResultSet rst = st.executeQuery("SELECT * FROM bulkorder;")) {

            // Loop through the result set and add each row to the model
            while (rst.next()) {
                model.addRow(new Object[]{
                    rst.getInt("BulkOrderID"),
                    rst.getDate("BulkOrderDate"),
                    rst.getInt("Qty"),
                    rst.getInt("TotalPrice"),
                    rst.getString("ProductName")
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_search7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCheckBulkOrderCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCheckBulkOrderCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCheckBulkOrderCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCheckBulkOrderCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCheckBulkOrderCashire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TextArea6;
    private javax.swing.JButton btn_search7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton txt_display6;
    private javax.swing.JTextField txt_orderid2;
    // End of variables declaration//GEN-END:variables
}
