/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class VHrDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VHrDashboard
     */
    public VHrDashboard() {
        initComponents();
    }
 @SuppressWarnings("unchecked")
    public void getReport() {
       try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "")) {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Model\\ExpenseReport1.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText("SELECT * FROM expense");
            jdesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(VHrDashboard.class.getName()).log(Level.SEVERE,null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_pm1 = new javax.swing.JButton();
        btn_pm4 = new javax.swing.JButton();
        btn_pm8 = new javax.swing.JButton();
        btn_pm9 = new javax.swing.JButton();
        btn_pm10 = new javax.swing.JButton();
        btn_pm5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_pm11 = new javax.swing.JButton();
        btn_pm12 = new javax.swing.JButton();
        btn_ExpenceReport = new javax.swing.JButton();
        btn_pm13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_pm1.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btn_pm1.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm1.setText("Manage  Expense");
        btn_pm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm1ActionPerformed(evt);
            }
        });

        btn_pm4.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm4.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm4.setText("Salary");
        btn_pm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm4ActionPerformed(evt);
            }
        });

        btn_pm8.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btn_pm8.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm8.setText("Send Feedback");
        btn_pm8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm8ActionPerformed(evt);
            }
        });

        btn_pm9.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm9.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm9.setText("Request leave");
        btn_pm9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm9ActionPerformed(evt);
            }
        });

        btn_pm10.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm10.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm10.setText("Profile");
        btn_pm10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm10ActionPerformed(evt);
            }
        });

        btn_pm5.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm5.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm5.setText("View Employe Ditails");
        btn_pm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm5ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(301, 337));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Images\\hr.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setText("HR Dashboard");

        btn_pm11.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm11.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm11.setText("Manage leave");
        btn_pm11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm11ActionPerformed(evt);
            }
        });

        btn_pm12.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm12.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm12.setText("Leave status");
        btn_pm12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm12ActionPerformed(evt);
            }
        });

        btn_ExpenceReport.setBackground(new java.awt.Color(0, 153, 153));
        btn_ExpenceReport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_ExpenceReport.setForeground(new java.awt.Color(255, 255, 255));
        btn_ExpenceReport.setText("Generate Expence Report");
        btn_ExpenceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExpenceReportActionPerformed(evt);
            }
        });

        btn_pm13.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm13.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm13.setText("NET Profit");
        btn_pm13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_pm5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_pm1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn_pm4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_pm11, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_pm10, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_pm9, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_pm12, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pm8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ExpenceReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pm13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(234, 234, 234))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_pm1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ExpenceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btn_pm13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(974, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm1ActionPerformed

        this.setVisible(false);
        VExpence pm=new VExpence();
        pm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm1ActionPerformed

    private void btn_ExpenceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExpenceReportActionPerformed
        this.setVisible(false);
        VExpenceReport pm=new VExpenceReport();
        pm.setVisible(true);    
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ExpenceReportActionPerformed

    private void btn_pm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm4ActionPerformed
       
        this.setVisible(false);
        VSalary vpmd =new VSalary();
        vpmd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_pm4ActionPerformed

    private void btn_pm8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm8ActionPerformed
       this.setVisible(false);
        VSendFeedBackHr vpmd =new VSendFeedBackHr();
        vpmd.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm8ActionPerformed

    private void btn_pm9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm9ActionPerformed
       this.setVisible(false);
        VRequestLeaveHr vpmd =new VRequestLeaveHr();
        vpmd.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm9ActionPerformed

    private void btn_pm10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm10ActionPerformed
     
        this.setVisible(false);
        VUserAcount vpmd =new VUserAcount();
        vpmd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_pm10ActionPerformed

    private void btn_pm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm5ActionPerformed
       this.setVisible(false);
        VEmployeeDetails vpmd =new VEmployeeDetails();
        vpmd.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        LoginPage vpmd =new LoginPage();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_pm11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm11ActionPerformed
        this.setVisible(false);
        VHrLeaveAccept vpmd =new VHrLeaveAccept();
        vpmd.setVisible(true);

        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_pm11ActionPerformed

    private void btn_pm12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm12ActionPerformed

 this.setVisible(false);
        VLeaveStetusHr vpmd =new VLeaveStetusHr();
        vpmd.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm12ActionPerformed

    private void btn_pm13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm13ActionPerformed

        this.setVisible(false);
        VNetProfit vpmd =new VNetProfit();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VHrDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ExpenceReport;
    private javax.swing.JButton btn_pm1;
    private javax.swing.JButton btn_pm10;
    private javax.swing.JButton btn_pm11;
    private javax.swing.JButton btn_pm12;
    private javax.swing.JButton btn_pm13;
    private javax.swing.JButton btn_pm4;
    private javax.swing.JButton btn_pm5;
    private javax.swing.JButton btn_pm8;
    private javax.swing.JButton btn_pm9;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
