/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author USER
 */
public class VNetProfit extends javax.swing.JFrame {

    /**
     * Creates new form VNetProfit
     */
    public VNetProfit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        com_date = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_totalorder = new javax.swing.JTextField();
        txt_totalbulkorder = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_expence = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_pettycash = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_profit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Net Profit");

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        com_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "This Week", "This Month", " " }));
        com_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_dateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total Profit");

        txt_totalorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalorderActionPerformed(evt);
            }
        });

        txt_totalbulkorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalbulkorderActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Date Range");

        jLabel6.setText("TotalOrder");

        jLabel7.setText("Total Bulk Order");

        txt_expence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_expenceActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Expence");

        txt_pettycash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pettycashActionPerformed(evt);
            }
        });

        jLabel9.setText("Total Petty Cash");

        jLabel10.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel11.setText("NET PROFIT");

        txt_profit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(com_date, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_totalorder, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4))
                    .addComponent(txt_totalbulkorder)
                    .addComponent(txt_expence)
                    .addComponent(txt_pettycash, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_profit, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(com_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_totalorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_totalbulkorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_expence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pettycash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel3)
                .addGap(230, 230, 230)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void calculateTotalsAndProfit() {
    String dateRange = com_date.getSelectedItem().toString();
    String dateCondition = "";

    // Define SQL date condition based on the selected range
    switch (dateRange) {
        case "Today":
            dateCondition = "CURDATE()";
            break;
        case "This Week":
            dateCondition = "YEARWEEK(CURDATE(), 1)";
            break;
        case "This Month":
            dateCondition = "MONTH(CURDATE())";
            break;
    }

    int totalOrder = 0, totalBulkOrder = 0, totalExpense = 0, totalPettyCash = 0, netProfit = 0;

    // SQL queries
    String orderQuery = "SELECT SUM(CAST(TotalPrice AS UNSIGNED)) FROM orders WHERE ";
    String bulkOrderQuery = "SELECT SUM(CAST(TotalPrice AS UNSIGNED)) FROM bulkorder WHERE ";
    String expenseQuery = "SELECT SUM(CAST(Amount AS UNSIGNED)) FROM expense WHERE ";
    String pettyCashQuery = "SELECT SUM(CAST(Amount AS UNSIGNED)) FROM pettycash WHERE ";

    if (dateRange.equals("Today")) {
        orderQuery += "DATE(OrderDate) = " + dateCondition;
        bulkOrderQuery += "DATE(BulkOrderDate) = " + dateCondition;
        expenseQuery += "DATE(Date) = " + dateCondition;
        pettyCashQuery += "DATE(Date) = " + dateCondition;
    } else if (dateRange.equals("This Week")) {
        orderQuery += "YEARWEEK(OrderDate, 1) = " + dateCondition;
        bulkOrderQuery += "YEARWEEK(BulkOrderDate, 1) = " + dateCondition;
        expenseQuery += "YEARWEEK(Date, 1) = " + dateCondition;
        pettyCashQuery += "YEARWEEK(Date, 1) = " + dateCondition;
    } else if (dateRange.equals("This Month")) {
        orderQuery += "MONTH(OrderDate) = " + dateCondition;
        bulkOrderQuery += "MONTH(BulkOrderDate) = " + dateCondition;
        expenseQuery += "MONTH(Date) = " + dateCondition;
        pettyCashQuery += "MONTH(Date) = " + dateCondition;
    }

    try {
        // Establish database connection using your details
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "");

        // Fetch Total Orders
        PreparedStatement orderStmt = conn.prepareStatement(orderQuery);
        ResultSet rsOrder = orderStmt.executeQuery();
        if (rsOrder.next()) {
            totalOrder = rsOrder.getInt(1);  // Store result as integer
        }
        txt_totalorder.setText(String.valueOf(totalOrder));

        // Fetch Total Bulk Orders
        PreparedStatement bulkOrderStmt = conn.prepareStatement(bulkOrderQuery);
        ResultSet rsBulkOrder = bulkOrderStmt.executeQuery();
        if (rsBulkOrder.next()) {
            totalBulkOrder = rsBulkOrder.getInt(1);  // Store result as integer
        }
        txt_totalbulkorder.setText(String.valueOf(totalBulkOrder));

        // Fetch Total Expense
        PreparedStatement expenseStmt = conn.prepareStatement(expenseQuery);
        ResultSet rsExpense = expenseStmt.executeQuery();
        if (rsExpense.next()) {
            totalExpense = rsExpense.getInt(1);  // Store result as integer
        }
        txt_expence.setText(String.valueOf(totalExpense));

        // Fetch Total Petty Cash
        PreparedStatement pettyCashStmt = conn.prepareStatement(pettyCashQuery);
        ResultSet rsPettyCash = pettyCashStmt.executeQuery();
        if (rsPettyCash.next()) {
            totalPettyCash = rsPettyCash.getInt(1);  // Store result as integer
        }
        txt_pettycash.setText(String.valueOf(totalPettyCash));

        // Calculate net profit as integer
        netProfit = (totalOrder + totalBulkOrder) - (totalExpense + totalPettyCash);
        txt_profit.setText(String.valueOf(netProfit));

        // Close all connections
        rsOrder.close();
        rsBulkOrder.close();
        rsExpense.close();
        rsPettyCash.close();
        conn.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error fetching data: " + e.getMessage());
    }
}


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        VHrDashboard vpmd =new VHrDashboard();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void com_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_dateActionPerformed

        calculateTotalsAndProfit();

        // TODO add your handling code here:
    }//GEN-LAST:event_com_dateActionPerformed

    private void txt_totalorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalorderActionPerformed

    private void txt_totalbulkorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalbulkorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalbulkorderActionPerformed

    private void txt_expenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_expenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_expenceActionPerformed

    private void txt_pettycashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pettycashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pettycashActionPerformed

    private void txt_profitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNetProfit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNetProfit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNetProfit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNetProfit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNetProfit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_date;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_expence;
    private javax.swing.JTextField txt_pettycash;
    private javax.swing.JTextField txt_profit;
    private javax.swing.JTextField txt_totalbulkorder;
    private javax.swing.JTextField txt_totalorder;
    // End of variables declaration//GEN-END:variables
}
