/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class VOrderReport extends javax.swing.JFrame {

    /**
     * Creates new form VOrderReport
     */
    public VOrderReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_prt = new javax.swing.JButton();
        btn_prw = new javax.swing.JButton();
        btn_prm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Report");

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btn_prt.setBackground(new java.awt.Color(0, 153, 153));
        btn_prt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_prt.setForeground(new java.awt.Color(255, 255, 255));
        btn_prt.setText("Order Report Anual ");
        btn_prt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prtActionPerformed(evt);
            }
        });

        btn_prw.setBackground(new java.awt.Color(0, 153, 153));
        btn_prw.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_prw.setForeground(new java.awt.Color(255, 255, 255));
        btn_prw.setText("Order Report Week ");
        btn_prw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prwActionPerformed(evt);
            }
        });

        btn_prm.setBackground(new java.awt.Color(0, 153, 153));
        btn_prm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_prm.setForeground(new java.awt.Color(255, 255, 255));
        btn_prm.setText("Order Report Monthly");
        btn_prm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_prm, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_prt, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_prw, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_prw, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_prm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_prt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       @SuppressWarnings("unchecked")
    public void getReport13() {
       try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "")) {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Model\\OWR.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText("SELECT OrderID, OrderDate, ProductID, Qty, TotalPrice, ProductName  FROM Orders WHERE OrderDate >= DATE_SUB(CURDATE(), INTERVAL 7 DAY);");
            jdesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(VProductManagerDashboard.class.getName()).log(Level.SEVERE,null, ex);
        }
    }
    
        @SuppressWarnings("unchecked")
    public void getReport14() {
       try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "")) {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Model\\OMR.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText("SELECT OrderID, OrderDate, ProductID, Qty, TotalPrice, ProductName  FROM Orders WHERE OrderDate >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);");
            jdesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(VProductManagerDashboard.class.getName()).log(Level.SEVERE,null, ex);
        }
    }
    
            @SuppressWarnings("unchecked")
    public void getReport15() {
       try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "")) {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Model\\OAR.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText("SELECT OrderID, OrderDate, ProductID, Qty, TotalPrice, ProductName  FROM Orders WHERE OrderDate >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);");
            jdesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(VProductManagerDashboard.class.getName()).log(Level.SEVERE,null, ex);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        VSalesManagerDashboard vpmd =new VSalesManagerDashboard();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_prtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prtActionPerformed

        getReport15();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_prtActionPerformed

    private void btn_prwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prwActionPerformed

        getReport13();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_prwActionPerformed

    private void btn_prmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prmActionPerformed

        getReport14();
    }//GEN-LAST:event_btn_prmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOrderReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prm;
    private javax.swing.JButton btn_prt;
    private javax.swing.JButton btn_prw;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
