/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class VSalesManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VSalesManagerDashboard
     */
    public VSalesManagerDashboard() {
        initComponents();
    }
@SuppressWarnings("unchecked")
    public void getReport() {
       try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "")) {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Model\\OrderReport1.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText("SELECT * FROM orders");
            jdesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(VProductManagerDashboard.class.getName()).log(Level.SEVERE,null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_MBulkOrder = new javax.swing.JButton();
        btn_pm3 = new javax.swing.JButton();
        btn_CheckBulckOrder = new javax.swing.JButton();
        btn_Feedback = new javax.swing.JButton();
        btn_RequestLeave = new javax.swing.JButton();
        btn_Profile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_pm12 = new javax.swing.JButton();
        btn_CheckBulckOrder1 = new javax.swing.JButton();
        btn_Profile1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_MBulkOrder.setBackground(new java.awt.Color(0, 153, 153));
        btn_MBulkOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_MBulkOrder.setForeground(new java.awt.Color(255, 255, 255));
        btn_MBulkOrder.setText("Manage Bulk Order");
        btn_MBulkOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MBulkOrderActionPerformed(evt);
            }
        });

        btn_pm3.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm3.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm3.setText("Generate Order Report");
        btn_pm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm3ActionPerformed(evt);
            }
        });

        btn_CheckBulckOrder.setBackground(new java.awt.Color(0, 153, 153));
        btn_CheckBulckOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_CheckBulckOrder.setForeground(new java.awt.Color(255, 255, 255));
        btn_CheckBulckOrder.setText("Check Bulk Order");
        btn_CheckBulckOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckBulckOrderActionPerformed(evt);
            }
        });

        btn_Feedback.setBackground(new java.awt.Color(0, 153, 153));
        btn_Feedback.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Feedback.setForeground(new java.awt.Color(255, 255, 255));
        btn_Feedback.setText("Send Feedback");
        btn_Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FeedbackActionPerformed(evt);
            }
        });

        btn_RequestLeave.setBackground(new java.awt.Color(0, 153, 153));
        btn_RequestLeave.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_RequestLeave.setForeground(new java.awt.Color(255, 255, 255));
        btn_RequestLeave.setText("Request leave");
        btn_RequestLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RequestLeaveActionPerformed(evt);
            }
        });

        btn_Profile.setBackground(new java.awt.Color(0, 153, 153));
        btn_Profile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_Profile.setText("Total Sales");
        btn_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfileActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(301, 337));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Images\\st.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setText("Sales Manager Dashboard");

        btn_pm12.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm12.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm12.setText("Leave  Status");
        btn_pm12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm12ActionPerformed(evt);
            }
        });

        btn_CheckBulckOrder1.setBackground(new java.awt.Color(0, 153, 153));
        btn_CheckBulckOrder1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_CheckBulckOrder1.setForeground(new java.awt.Color(255, 255, 255));
        btn_CheckBulckOrder1.setText("View  Customer Payment");
        btn_CheckBulckOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckBulckOrder1ActionPerformed(evt);
            }
        });

        btn_Profile1.setBackground(new java.awt.Color(0, 153, 153));
        btn_Profile1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Profile1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Profile1.setText("Profile");
        btn_Profile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Profile1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MBulkOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CheckBulckOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CheckBulckOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pm3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_RequestLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pm12, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(btn_MBulkOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_CheckBulckOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_CheckBulckOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_pm3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btn_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_RequestLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_pm12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MBulkOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MBulkOrderActionPerformed

        this.setVisible(false);
        VBulkOrder pm=new VBulkOrder();
        pm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MBulkOrderActionPerformed

    private void btn_pm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm3ActionPerformed
        
                       this.setVisible(false);
        VOrderReport pm=new VOrderReport();
        pm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm3ActionPerformed

    private void btn_CheckBulckOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckBulckOrderActionPerformed

           this.setVisible(false);
        VCheckBulkOrderCashire pm=new VCheckBulkOrderCashire();
        pm.setVisible(true);
        // TODO add your handlin
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CheckBulckOrderActionPerformed

    private void btn_FeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FeedbackActionPerformed

        
         this.setVisible(false);
        VSendFeedBacksm pm=new VSendFeedBacksm();
        pm.setVisible(true);       
                
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_FeedbackActionPerformed

    private void btn_RequestLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RequestLeaveActionPerformed
       
        this.setVisible(false);
        VRequestLeavesm vpmd =new VRequestLeavesm();
        vpmd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_RequestLeaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        LoginPage vpmd =new LoginPage();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_pm12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm12ActionPerformed
         this.setVisible(false);
        VLeaveStetusSm vpmd =new VLeaveStetusSm();
        vpmd.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_pm12ActionPerformed

    private void btn_CheckBulckOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckBulckOrder1ActionPerformed
  this.setVisible(false);
        VCustomerPayemnt vpmd =new VCustomerPayemnt();
        vpmd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CheckBulckOrder1ActionPerformed

    private void btn_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfileActionPerformed
        this.setVisible(false);
        VTotalsales vpmd =new VTotalsales();
        vpmd.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btn_ProfileActionPerformed

    private void btn_Profile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Profile1ActionPerformed
       
        this.setVisible(false);
        VUserAcount vpmd =new VUserAcount();
        vpmd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Profile1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VSalesManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CheckBulckOrder;
    private javax.swing.JButton btn_CheckBulckOrder1;
    private javax.swing.JButton btn_Feedback;
    private javax.swing.JButton btn_MBulkOrder;
    private javax.swing.JButton btn_Profile;
    private javax.swing.JButton btn_Profile1;
    private javax.swing.JButton btn_RequestLeave;
    private javax.swing.JButton btn_pm12;
    private javax.swing.JButton btn_pm3;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
