/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class VStockManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VStockManagerDashboard
     */
    public VStockManagerDashboard() {
        initComponents();
    }
    @SuppressWarnings("unchecked")
    public void getReport() {
       try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "")) {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Model\\StockReport1.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText("SELECT * FROM stock");
            jdesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(VStockManagerDashboard.class.getName()).log(Level.SEVERE,null, ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    public void getReport1() {
       try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ims", "root", "")) {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Model\\SupplierReport1.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText("SELECT * FROM supplier");
            jdesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(VStockManagerDashboard.class.getName()).log(Level.SEVERE,null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_AddSupplier = new javax.swing.JButton();
        btn_AddStock = new javax.swing.JButton();
        btn_chckStock = new javax.swing.JButton();
        btn_SupReport = new javax.swing.JButton();
        btn_GenReport = new javax.swing.JButton();
        btn_feedback = new javax.swing.JButton();
        btn_UpdateProfile = new javax.swing.JButton();
        btn_RLeave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_pm13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_AddSupplier.setBackground(new java.awt.Color(0, 153, 153));
        btn_AddSupplier.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_AddSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddSupplier.setText("Add Suppler ");
        btn_AddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddSupplierActionPerformed(evt);
            }
        });

        btn_AddStock.setBackground(new java.awt.Color(0, 153, 153));
        btn_AddStock.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_AddStock.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddStock.setText("Add Stock");
        btn_AddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddStockActionPerformed(evt);
            }
        });

        btn_chckStock.setBackground(new java.awt.Color(0, 153, 153));
        btn_chckStock.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_chckStock.setForeground(new java.awt.Color(255, 255, 255));
        btn_chckStock.setText("Check Stock Details");
        btn_chckStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chckStockActionPerformed(evt);
            }
        });

        btn_SupReport.setBackground(new java.awt.Color(0, 153, 153));
        btn_SupReport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_SupReport.setForeground(new java.awt.Color(255, 255, 255));
        btn_SupReport.setText("Generate Supplier Detail Report");
        btn_SupReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SupReportActionPerformed(evt);
            }
        });

        btn_GenReport.setBackground(new java.awt.Color(0, 153, 153));
        btn_GenReport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_GenReport.setForeground(new java.awt.Color(255, 255, 255));
        btn_GenReport.setText("Generate Stock Report");
        btn_GenReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenReportActionPerformed(evt);
            }
        });

        btn_feedback.setBackground(new java.awt.Color(0, 153, 153));
        btn_feedback.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_feedback.setForeground(new java.awt.Color(255, 255, 255));
        btn_feedback.setText("Send Feedback");
        btn_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feedbackActionPerformed(evt);
            }
        });

        btn_UpdateProfile.setBackground(new java.awt.Color(0, 153, 153));
        btn_UpdateProfile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_UpdateProfile.setForeground(new java.awt.Color(255, 255, 255));
        btn_UpdateProfile.setText("Update Profile");
        btn_UpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateProfileActionPerformed(evt);
            }
        });

        btn_RLeave.setBackground(new java.awt.Color(0, 153, 153));
        btn_RLeave.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_RLeave.setForeground(new java.awt.Color(255, 255, 255));
        btn_RLeave.setText("Request leave");
        btn_RLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RLeaveActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(301, 337));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Images\\st.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setText("Stock Manager Dashboard");

        btn_pm13.setBackground(new java.awt.Color(0, 153, 153));
        btn_pm13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pm13.setForeground(new java.awt.Color(255, 255, 255));
        btn_pm13.setText("Leave  Status");
        btn_pm13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pm13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_AddStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_AddSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn_pm13, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_RLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_UpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SupReport, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_GenReport, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_chckStock, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(172, 172, 172))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addComponent(btn_AddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_AddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_chckStock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_GenReport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_SupReport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_UpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_RLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pm13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddSupplierActionPerformed

        this.setVisible(false);
         VSupplier vs=new VSupplier();
        vs.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddSupplierActionPerformed

    private void btn_AddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddStockActionPerformed

         this.setVisible(false);
         VStock vs=new VStock();
        vs.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddStockActionPerformed

    private void btn_chckStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chckStockActionPerformed
       
        this.setVisible(false);
        VCheckStock vpmd =new VCheckStock();
        vpmd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_chckStockActionPerformed

    private void btn_SupReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SupReportActionPerformed
        getReport1();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SupReportActionPerformed

    private void btn_GenReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenReportActionPerformed
   this.setVisible(false);
        VStockReport vpmd =new VStockReport();
        vpmd.setVisible(true);  // TODO add your handling code here:     
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_GenReportActionPerformed

    private void btn_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feedbackActionPerformed
      this.setVisible(false);
        VSendFeedBackStockManager vpmd =new VSendFeedBackStockManager();
        vpmd.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_feedbackActionPerformed

    private void btn_UpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateProfileActionPerformed
     
        this.setVisible(false);
        VRequestLeavesm vpmd =new VRequestLeavesm();
        vpmd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_UpdateProfileActionPerformed

    private void btn_RLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RLeaveActionPerformed
      this.setVisible(false);
        VRequestLeaveStockManger vpmd =new VRequestLeaveStockManger();
        vpmd.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_RLeaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        LoginPage vpmd =new LoginPage();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_pm13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pm13ActionPerformed
        this.setVisible(false);
        VLeaveStetusStockManager vpmd =new VLeaveStetusStockManager();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pm13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VStockManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VStockManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VStockManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VStockManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VStockManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddStock;
    private javax.swing.JButton btn_AddSupplier;
    private javax.swing.JButton btn_GenReport;
    private javax.swing.JButton btn_RLeave;
    private javax.swing.JButton btn_SupReport;
    private javax.swing.JButton btn_UpdateProfile;
    private javax.swing.JButton btn_chckStock;
    private javax.swing.JButton btn_feedback;
    private javax.swing.JButton btn_pm13;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
