/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CStock;
import Model.MDBConnection;
import javax.swing.JOptionPane;
import java.sql.*;



/**
 *
 * @author USER
 */
public class VStock extends javax.swing.JFrame {

    /**
     * Creates new form VStock
     */
    public VStock() {
        initComponents();
        id_autoincrement();
         date_stock.setDate(new java.util.Date());
    }
    public void id_autoincrement(){
        
      try {
        Connection conn = MDBConnection.createConnection();
        String sql = "SELECT MAX(StockID) FROM Stock";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        int nextId = 1;  // Default ID if no records are found
        
        if (rs.next()) {
            int maxId = rs.getInt(1);
            nextId = maxId + 1;
        }
        
        // Set the nextId value to the txt_productid text field
        txt_stockid.setText(String.valueOf(nextId));

        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    }
    public void clearField(){
    
    
       // txt_stockid.setText(null);
        
        txt_qty.setText(null);
        txt_productid.setText(null);
        txt_supplierid.setText(null);
        date_stock.setDate(null);
        txt_cqty.setText("");
        txt_productname.setText("");
        txt_suppliername.setText("");
        txt_total.setText("");
        txt_currentqty.setText("");
        
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_stockid = new javax.swing.JTextField();
        txt_membername = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Update = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_Add = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        txt_productname = new javax.swing.JTextField();
        txt_productid = new javax.swing.JTextField();
        txt_supplierid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_suppliername = new javax.swing.JTextField();
        txt_membername2 = new javax.swing.JLabel();
        date_stock = new com.toedter.calendar.JDateChooser();
        txt_membername1 = new javax.swing.JLabel();
        txt_cqty = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_membername3 = new javax.swing.JLabel();
        txt_currentqty = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_unitprice = new javax.swing.JTextField();
        txt_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Stock ID");

        txt_stockid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stockidActionPerformed(evt);
            }
        });

        txt_membername.setText("Qty");

        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });

        jLabel3.setText("Product ID");

        jLabel6.setText("Product Name");

        btn_Update.setBackground(new java.awt.Color(0, 153, 153));
        btn_Update.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 153, 153));
        btn_clear.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel8.setText("Supplier ID");

        btn_Add.setBackground(new java.awt.Color(0, 153, 153));
        btn_Add.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Delete.setBackground(new java.awt.Color(0, 153, 153));
        btn_Delete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        txt_productname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productnameActionPerformed(evt);
            }
        });

        txt_productid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productidActionPerformed(evt);
            }
        });

        txt_supplierid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_supplieridActionPerformed(evt);
            }
        });

        jLabel9.setText("Supplier Name");

        txt_suppliername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suppliernameActionPerformed(evt);
            }
        });

        txt_membername2.setText("Date");

        txt_membername1.setText("Current Qty");

        txt_cqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cqtyActionPerformed(evt);
            }
        });

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        txt_membername3.setText("Total");

        txt_currentqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_currentqtyActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(301, 337));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\Ims2\\MSI\\src\\Images\\st.png")); // NOI18N

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setText("Stock");

        jLabel10.setText("Unit Price");

        txt_unitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unitpriceActionPerformed(evt);
            }
        });

        txt_return.setBackground(new java.awt.Color(0, 153, 153));
        txt_return.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txt_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_return.setText("Return");
        txt_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cqty, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txt_productid, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txt_stockid, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_membername2))))
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_supplierid, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_unitprice, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_membername1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_membername3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(txt_membername)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_currentqty, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(btn_clear))
                                    .addComponent(btn_Add))))
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_return)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btn_Update)
                                .addGap(35, 35, 35)
                                .addComponent(btn_Delete)))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(339, 339, 339))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(50, 50, 50)
                .addComponent(txt_cqty, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_stockid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txt_membername2))
                    .addComponent(date_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_productid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_supplierid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_unitprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_currentqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_membername1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_membername))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_membername3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Delete)
                    .addComponent(btn_Update)
                    .addComponent(txt_return)
                    .addComponent(btn_clear)
                    .addComponent(btn_Add))
                .addGap(117, 117, 117))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        VStockManagerDashboard vpmd =new VStockManagerDashboard();
        vpmd.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_currentqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_currentqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_currentqtyActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_cqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cqtyActionPerformed

    private void txt_suppliernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suppliernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_suppliernameActionPerformed

    private void txt_supplieridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_supplieridActionPerformed

        int supplierid =Integer.parseInt(txt_supplierid.getText());
        if (supplierid==0) {
            JOptionPane.showMessageDialog(null, "Please enter the supplier ID to view details");
            return;
        }

        try {
            Connection conn = MDBConnection.createConnection();
            String sql = "SELECT SupplierName FROM supplier WHERE SupplierID = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, supplierid);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Assuming these text fields are defined and used for displaying member details

                txt_suppliername.setText(rs.getString("SupplierName"));

            } else {
                JOptionPane.showMessageDialog(null, "Supplier ID not found");
            }

            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error retrieving Supplier details: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_supplieridActionPerformed

    private void txt_productidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productidActionPerformed

        int productid = Integer.parseInt(txt_productid.getText());

        if (productid == 0) {
            JOptionPane.showMessageDialog(null, "Please enter the product ID to view details");
            return;
        }

        try {
            try (Connection conn = MDBConnection.createConnection()) {
                String sql = "SELECT ProductName,Qty,Price FROM Product WHERE ProductID = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, productid);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txt_productname.setText(rs.getString("ProductName"));
                    int unitprice = rs.getInt("Price");
                    txt_unitprice.setText(String.valueOf(unitprice));
                    int currentqty = rs.getInt("Qty");
                    txt_currentqty.setText(String.valueOf(currentqty));

                } else {
                    JOptionPane.showMessageDialog(null, "Product ID not found");
                }       }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error retrieving product details: " + e.getMessage());
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_txt_productidActionPerformed

    private void txt_productnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productnameActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed

        int stockid=Integer.parseInt(txt_stockid.getText());
        CStock cs=new CStock();
        cs.deleteSupplier(stockid);
        clearField();
        id_autoincrement();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed

       

        int stockid=Integer.parseInt(txt_stockid.getText());
        java.util.Date utilStock = date_stock.getDate();
        java.sql.Date sqlStockDate = new java.sql.Date(utilStock.getTime());
        int qty = Integer.parseInt(txt_qty.getText());
        int productid =Integer.parseInt(txt_productid.getText());
        int supplierid =Integer.parseInt(txt_supplierid.getText());
        String productname=txt_productname.getText();
        String suppliername=txt_suppliername.getText();
        int price=Integer.parseInt(txt_total.getText());

        CStock cs=new CStock();
        cs.addStock(qty, productid, supplierid, sqlStockDate, price);

        id_autoincrement();
        clearField();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearField();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // id_autoincrement();

        int stockid=Integer.parseInt(txt_stockid.getText());
        java.util.Date utilStock = date_stock.getDate();
        java.sql.Date sqlStockDate = new java.sql.Date(utilStock.getTime());
        int qty = Integer.parseInt(txt_qty.getText());
        int productid =Integer.parseInt(txt_productid.getText());
        int supplierid =Integer.parseInt(txt_supplierid.getText());
        String productname=txt_productname.getText();
        String suppliername=txt_suppliername.getText();

        CStock cs=new CStock();
        cs.updateStock(stockid, qty, productid, supplierid, sqlStockDate);

        id_autoincrement();
        clearField();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed

        int qty = Integer.parseInt(txt_qty.getText());
        int productid = Integer.parseInt(txt_productid.getText());

        if (qty == 0) {
            JOptionPane.showMessageDialog(null, "Please enter the product ID to view details");
            return;
        }

        try {
            try (Connection conn = MDBConnection.createConnection()) {
                String sql = "SELECT Price FROM Product WHERE ProductID = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, productid);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {

                    int price = rs.getInt("Price");
                    int total;
                    total = price * qty;
                    txt_total.setText(String.valueOf(total));

                } else {
                    JOptionPane.showMessageDialog(null, "Product ID not found");
                }       }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error retrieving product details: " + e.getMessage());
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void txt_stockidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stockidActionPerformed

        int stockid =Integer.parseInt(txt_stockid.getText());
        if (stockid==0) {
            JOptionPane.showMessageDialog(null, "Please enter the supplier ID to view details");
            return;
        }

        try {
            Connection conn = MDBConnection.createConnection();
            String sql = "SELECT StockID, Qty, ProductID,SupplierID,StockDate FROM Stock WHERE StockID = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, stockid);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Assuming these text fields are defined and used for displaying member details

                int qty = rs.getInt("Qty");
                txt_qty.setText(String.valueOf(qty));
                int productid=rs.getInt("ProductID");
                txt_productid.setText(String.valueOf(productid));
                int supplieid=rs.getInt("SupplierID");
                txt_supplierid.setText(String.valueOf(supplieid));
                Date date=rs.getDate("StockDate");
                date_stock.setDate(date);
                

            } else {
                JOptionPane.showMessageDialog(null, "Stock ID not found");
            }

            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error retrieving Stock details: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stockidActionPerformed

    private void txt_unitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unitpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitpriceActionPerformed

    private void txt_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_returnActionPerformed
        int qty = Integer.parseInt(txt_qty.getText());
int productid = Integer.parseInt(txt_productid.getText());

if (qty == 0) {
    JOptionPane.showMessageDialog(null, "Please enter a valid quantity to return");
    return;
}

try {
    Connection conn = MDBConnection.createConnection();
    String sqlProduct = "SELECT Qty FROM Product WHERE ProductID = ?";
    PreparedStatement pstProduct = conn.prepareStatement(sqlProduct);
    pstProduct.setInt(1, productid);
    ResultSet rs = pstProduct.executeQuery();

    if (rs.next()) {
        int currentQty = rs.getInt("Qty");

        if (currentQty < qty) {
            JOptionPane.showMessageDialog(null, "Return quantity exceeds current stock!");
            return;
        }

        // Calculate the new quantity after the return
        int newQty = currentQty - qty;

        // Update the product quantity in the Product table
        String updateQtySQL = "UPDATE Product SET Qty = ? WHERE ProductID = ?";
        PreparedStatement pstUpdate = conn.prepareStatement(updateQtySQL);
        pstUpdate.setInt(1, newQty);
        pstUpdate.setInt(2, productid);
        pstUpdate.executeUpdate();

        // Insert return details into the Return table
        String insertReturnSQL = "INSERT INTO ReturnStock (StockID, ProductID, SupplierID, ReturnDate, ReturnQty, Price) VALUES (?, ?, ?, CURDATE(), ?, ?)";
PreparedStatement pstReturn = conn.prepareStatement(insertReturnSQL);
pstReturn.setInt(1, Integer.parseInt(txt_stockid.getText()));
pstReturn.setInt(2, Integer.parseInt(txt_productid.getText()));
pstReturn.setInt(3, Integer.parseInt(txt_supplierid.getText()));
pstReturn.setInt(4, qty);
pstReturn.setInt(5, Integer.parseInt(txt_unitprice.getText()));  // Assuming Price comes from txt_unitprice
pstReturn.executeUpdate();


        JOptionPane.showMessageDialog(null, "Stock returned successfully and Product Qty updated");

    } else {
        JOptionPane.showMessageDialog(null, "Product ID not found");
    }

    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
        clearField();


        // TODO add your handling code here:
    }//GEN-LAST:event_txt_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_clear;
    private com.toedter.calendar.JDateChooser date_stock;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_cqty;
    private javax.swing.JTextField txt_currentqty;
    private javax.swing.JLabel txt_membername;
    private javax.swing.JLabel txt_membername1;
    private javax.swing.JLabel txt_membername2;
    private javax.swing.JLabel txt_membername3;
    private javax.swing.JTextField txt_productid;
    private javax.swing.JTextField txt_productname;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JButton txt_return;
    private javax.swing.JTextField txt_stockid;
    private javax.swing.JTextField txt_supplierid;
    private javax.swing.JTextField txt_suppliername;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_unitprice;
    // End of variables declaration//GEN-END:variables
}
